### ISSUE TITLE
Cannot Access to Playground - Privacy Error

### ISSUE THREAD

**Issue by firattamurlc** [livekit/agents-playground#121]
### Describe the bug

<img width="1249" alt="Screenshot 2024-12-24 at 7 26 26 PM" src="https://github.com/user-attachments/assets/1b783fd3-8469-4aa4-bd9e-76318f1e85d9" />

### Reproduction

Visit -> https://agents-playground.livekit.io/

### System Info

```shell
MacOS
```

### Severity

blocking all usage of LiveKit

**Comment by davidzhao** [comment]
the SSL cert had expired.. it's fixed now.
